### PR TITLE
minor address-watcher fix

### PR DESCRIPTION
**Pull request by 0x3bfc**

### CODE REVIEW

**Comment by sept-en** [comment]
JS supports underscores as separators in numerical literals and it's used here for readability purposes so is there any reason why we need to change this?

**Comment by 0x3bfc** [comment]
> JS supports underscores as separators in numerical literals and it's used here for readability purposes so is there any reason why we need to change this?

The only reason is that it fails when I start the cli `cli/index.js --help`

```
$ cli/index.js --help
/Users/ahmedali/Desktop/work/aurora/rainbow-bridge/utils/address-watcher.js:70
      await sleep(1_000)
                  ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/ahmedali/Desktop/work/aurora/rainbow-bridge/cli/commands/start/address-watcher.js:3:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/ahmedali/Desktop/work/aurora/rainbow-bridge/cli/index.js:18:35)
```

**Comment by sept-en** [comment]
What Node.js version are you using? I think you might be using an outdated one. I have never experienced this.

**Comment by sept-en** [comment]
Works fine with the Node version >= 12. Honestly, I'd prefer to update the Readme to suggest using version >= 12 as I think there are probably other things we can find that won't work for the Node v10.

**Review by mfornet — APPROVED** [review]

**Pull request merged**
